### ISSUE TITLE
Website URL in the Google Chrome extension 

### ISSUE THREAD

**Issue by andrasfuchs** [Nebukam/steam-game-finder#1] opened 2021-12-18 19:45 UTC
The website URL in the Google extension is https://nebukam.github.io/steam-game-finder/ which is a 404.

The URL that seems to work is https://github.com/Nebukam/steam-game-finder.

**Comment by Nebukam** [comment] 2021-12-19 16:04
Hey @andrasfuchs -- thanks for the heads-up.
That was intended as the currently dead link was meant to have a landing page that link to the different extensions + pwa that is yet to come. Will close this once it's done.

**Comment by Nebukam** [comment] 2021-12-23 07:49
(made a redirect at the existing URL, easier than udpating the marketplace infos -_-)

**Closed by Nebukam** 2021-12-23 07:49 UTC
